KNOWN_SKILLS = [
    "Python",
    "SQL",
    "Java",
    "JavaScript",
    "TypeScript",
    "C++",
    "Go",
    "Rust",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "AWS",
    "Azure",
    "GCP",
    "Docker",
    "Kubernetes",
    "TensorFlow",
    "PyTorch",
    "scikit-learn",
    "pandas",
    "NumPy",
    "FastAPI",
    "Flask",
    "Django",
    "React",
    "Node.js",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "Git",
    "Linux",
    "Spark",
    "Kafka",
    "Airflow",
]
